### ISSUE TITLE
Posh-Git makes VS 2015 hang

### ISSUE THREAD

**Issue by persalmi** [dahlbyk/posh-git#218]
If posh-git is installed and activated in the default PowerShell profile (profile.ps1 or NuGet_profile.ps1) it makes Visual Studio 2015 crash when the Package Manager Console windows is opened inside Visual Studio 2015.

Something in the posh-git package causes the PMC window to lock up the entire studio application and you have to kill it from the task manager.

To reproduce just make sure  "posh-git\profile.example.ps1" is started from the profile.ps1 script and start VS 2015 and then open the Package Manager Console.

I worked around the issue by moving the posh-git profile activation to Microsoft.PowerShell_profile.ps1 that is not used by the Package Manager Console window.

**Comment by dahlbyk** [comment]
Fascinating... I wonder if it has something to do with attempts to start Pageant or ssh-agent?

Suppose I should download VS2015 and check this out.

**Comment by paulmarsy** [comment]
There appears to be two problems, firstly if git.exe isn't in the path when posh-git it ipmo'd a warning is given that it can't be found (just a general issue on my machine as I have everything in portable mode)
![git missing](https://cloud.githubusercontent.com/assets/1769405/9981223/a6235e88-5fae-11e5-9af1-f636ac3b1011.PNG)

For the actual hang, luckily it isn't in Write-VcsStatus but when trying to write-host the provider path, here I have build up the prompt function over time until the line which causes the crash was found:
![crash cause](https://cloud.githubusercontent.com/assets/1769405/9981237/74c96cf0-5faf-11e5-90c6-0e243dbf391a.png)

To find which part causes the crash I experimented a bit and it looks like the use of 'Write-Host' in the prompt of the Package Manager Console Window appears to be a no-no:
![write-host in prompt](https://cloud.githubusercontent.com/assets/1769405/9981256/391becf4-5fb0-11e5-901d-a8ea7f7e9e3e.PNG)

**Comment by dahlbyk** [comment]
Don't have VS2015 on this machine... Do you get the same behavior if you return a `string` after?

```powershell
function global:prompt { Write-Host "test"; return "PM>" }
```

**Comment by paulmarsy** [comment]
It appears the use of any 'Out-' cmdlets in the prompt function causes the host to hang, here I cause the prompt to hang by using Out-File which should have no effect on the prompt
![out problem](https://cloud.githubusercontent.com/assets/1769405/9981464/ba8c5e04-5fb5-11e5-95a9-8bf8978d5997.PNG)

The common theme became apparent when using 'Out-String' to try and return information from the prompt rather than attempting to render it directly:
![out-string](https://cloud.githubusercontent.com/assets/1769405/9981492/9c025712-5fb6-11e5-88d0-9ee422f0db80.PNG)

Additionally whilst it does initially appear that Visual Studio has crashed, when I went back to a previously opened instance that I hadn't closed the prompt had returned, so it isn't causing Visual Studio to crash, just the terminal becomes painfully slow to render the prompt.

**Comment by dahlbyk** [comment]
Relevant Nuget issue: https://github.com/NuGet/Home/issues/917

**Comment by paulmarsy** [comment]
Good find, it looks like they have a fix for it however it was done a few months ago, initially marked for the 3.2 milestone then moved to the 3.1 milestone.

However I have just installed the latest NuGet tools 3.2.0 (from 3.0.0) and it still appears to be problem.

It hasn't been raised before so I don't believe it warrants implementing the following - however we could implement a blacklist for the NuGet host to warn users of the issue?

**Comment by remcoros** [comment]
It has been pushed back to 3.3-beta a while ago. Don't know why though as not being able to set the prompt in the nuget console is a pretty major bug if you ask me.

**Comment by theaquamarine** [comment]
NuGet has fixed this with 3.3 (https://github.com/NuGet/Home/issues/917, https://github.com/NuGet/NuGet.Client/pull/73), so closing the issue.
