### ISSUE TITLE
Can't provide OTP when pushing

### ISSUE THREAD

**Issue by davidobrien1985** [dahlbyk/posh-git#276]
How do I provide my OTP / MFA token to the auth prompt on Windows?
The standard Windows prompt only accepts username and password.

I do have this module here https://github.com/davidobrien1985/githubconnect with a command to `Connect-Github` but that surely isn't the answer to this problem.

**Comment by theaquamarine** [comment]
If you've got 2FA auth turned on for GitHub and you're trying to push to a https remote, you need to use a personal access token rather than a password.
https://help.github.com/articles/providing-your-2fa-authentication-code/#through-the-command-line
https://help.github.com/articles/which-remote-url-should-i-use/#when-2fa-is-enabled
https://help.github.com/articles/creating-an-access-token-for-command-line-use/

In my experience, most people tend to use ssh remotes, hence all the work for supporting ssh agents in things like posh-git, but really this is a git/github issue so I'm going to close.
