### ISSUE TITLE
Posh-git can not see the current branch working through a symbolic link

### ISSUE THREAD

**Issue by AcruvalTotalProduce** [dahlbyk/posh-git#294]
The simbolic link reference can not sincronice very well
It get
C:\dev\project [(FTR-feature)]>
instead
C:\dev\project [FTR-feature↑ +4 ~0 -0 !]>

The project was clone to the parent pointed by project. It's the same structure but in another drive.

**Comment by dahlbyk** [comment]
Sorry for the delayed response here... We're pretty dependent on `git status` here, so if `git status -sb` isn't showing you the expected status, I'm not sure what we can do.

That said, I'm not sure why `git status` wouldn't be able to correctly resolve `HEAD` being a symbolic link?

**Comment by AcruvalTotalProduce** [comment]
Hi Keith.
Happy New Year
How much are you payed to develop this code? So thanks for you code and don’t apology for delay.
I can ask  why git status cannot resolve HEAD  being a symbolic link, if you didn’t that before.

PD.
I  tried to used symbolic link to put obj directories and files in a RAM disk to improve compiling time. But despite the symbolic link problem, having a SSD, the bottleneck, in my case, is the processor, even it didn’t look heavily used (it is but the load are not well split in all the cores)

Thanks

Antonio de la Cruz
acruval@totalproduce.com<mailto:acruval@totalproduce.com>
1 Beresford Street
Dublin D07 T611
[cid:image001.png@01CF1E96.DBBD2ED0]

**Comment by dahlbyk** [comment]
> How much are you payed to develop this code? So thanks for you code and don’t apology for delay.

That's fair.

So the neat part about knowing Git internals is that I definitely transposed "symoblic link" to "symbolic reference" in my head, and got confused. `git status` certainly should work with symbolic **references**, but that's not at all what you asked.

Handling symbolic **links** in Git on Windows is a [common question](http://stackoverflow.com/search?q=git+symlink), and the short version is that Git views the link as a normal blob with contents and a file mode that is added to the repository. Their behavior should be pretty stable now on platforms that support POSIX symlinks, but not on Windows.

I'm going to go ahead and close this issue, since it's not specific to posh-git, but feel free to follow up with any specific questions or results from your research.
