### ISSUE TITLE
LF normalization disabled in .gitattributes

### ISSUE THREAD

**Issue by rkeithhill** [dahlbyk/posh-git#334]
I see this in .gitattributes:
```
# Disable LF normalization for all files
* -text
```
Why do we do this?  When I git clone the repo on Linux and test/edit files, the line endings are screwed up in VI.

**Comment by dahlbyk** [comment]
> When I git clone the repo on Linux and test/edit files, the line endings are screwed up in VI.

What do you mean by "line endings are screwed up in VI"? I would expect it to detect CRLF files without issue.

> Why do we do this? 

In short, because I didn't want to deal with a commit to normalize line endings in the repo (merge conflicts for every open PR). That said, I just stumbled on [`merge.renormalize`](https://git-scm.com/docs/gitattributes#_merging_branches_with_differing_checkin_checkout_attributes) (which has [existed since **2010**?!](https://github.com/git/git/commit/f217f0e86dc7bacc5dc127982eaadca758b558ce)) that should help mitigate that issue. I wonder if GitHub supports that by default?

**Comment by rkeithhill** [comment]
All of the source files show `^M` (carriage return) in VI on Ubuntu.  Normally, the repo would clone down on Linux with just LF for new lines.  Not a huge deal.  Was just wondering if it would be worth changing this for an eventual 1.0.0 release as I (and hopefully others) edit & test the module directly on Linux.
