### ISSUE TITLE
Should posh-git 1.0 support PowerShell >= 5.0 or >= 3.0

### ISSUE THREAD

**Issue by rkeithhill** [dahlbyk/posh-git#429]
What would we miss out on by supporting back to PowerShell v3?  I don't think ANSI escape sequences should factor into this as PowerShell v5 will run on systems (like Windows 7) that will not support ANSI escape sequences. 

Advantages of supporting only >= 5.0

1. Support for classes which might make it easier to group related GitPromptSettings
2. Move to built-in Register-ArgumentCompleter command (play well with other module's tab completers)
3. Given that WMF 5/5.1 is available for Windows 7 / Windows Server 2008 R2 and we have posh-git 0.7x to support PS v2/3/4 maybe there isn't enough reason to support PS versions < 5?

Any other arguments for supporting >= 5.0 or any arguments for supporting v3?

**Comment by lzybkr** [comment]
I expect you'll get complaints, but as you mentioned, those folks can live with 0.7.x - it's in good shape so that seems acceptable.

More random thoughts:

* The built-in `RegisterArgumentCompleter` is nice, but you could require `TabExpansionPlusPlus` and work with V3.
* I'd always envisioned argument completion for `git` [looking like this - for net.exe](https://github.com/lzybkr/TabExpansionPlusPlus/blob/master/WindowsExe.ArgumentCompleters.ps1#L62). V5 doesn't have the extra helpers that you'd want.
* You could use the much faster `[sometype]::new()` syntax if requiring >= 5.0.

**Comment by rkeithhill** [comment]
I'm leaning towards supporting v3 since we could get class support using Add-Type (not as nice but should work) and, as you say, we could use TabExpansionPlusPlus to hook into Register-ArgumentCompleter.  Although support for tab-completing parameters (- and --) was recently added to posh-git.  Does TabExpansionPlusPlus support that?  

Also, it would be nice if TabExpansionPlusPlux installed into v5/6 without requiring `-AllowClobber` - https://github.com/lzybkr/TabExpansionPlusPlus/issues/78

All that said, I think the priorities for v1.0 are the following (in order of importance):

1. Support cross-platform PowerShell - which means making the prompt handling use either `Write-Host` or `ANSI escape sequences` depending on the platform.
2. Improve the customization experience over the current `$GitPromptSettings` which is currently slammed into a Global and doesn't use module exported variable.  Here we could use a combination of classes to group related properties (and render to ANSI escape sequenced str) and commands like `Get/Set-PoshGitOption`.
3. Modernize posh-git tab-completion.

**Comment by dahlbyk** [comment]
> Modernize posh-git tab-completion.

Is this an actual UX challenge, or just for our developer benefit? I may just be numb to the pain of maintaining these RegEx…

**Comment by dahlbyk** [comment]
The other 1.0 priority I will add to the list is to kick the SSH Agent stuff out of this repo.

**Comment by lzybkr** [comment]
There is a user benefit to building on `Register-ArgumentCompleter` - tab completion will start working in places it might not have before, e.g.

```PowerShell
if ($a) { git checkout <TAB> }
```

You could still use your regex parsing if you wanted, you'd just change how you get the command line slightly - you'll get just your command in the Ast instead of the full command line.

That said, you might find more folks contributing if it was easier.

**Comment by rkeithhill** [comment]
regex or not, I do like that tab-completion works in more contexts.

RE SSH Agent, @dahlbyk  do you want to host this?  If so, what would we call it?  `posh-git-ssh`?  There is already a [posh-ssh](https://www.powershellgallery.com/packages/Posh-SSH/1.7.7) on the PowerShell Gallery but it doesn't seem to deal with the agent or keys.  

BTW are the posh-git SSH commands specific to `GitHub for Windows`?  Sorry for the dumb questions, I've only used http with Git.

**Comment by nitin88** [comment]
I am actually in favor of dropping support of Powershell < 5.0.

Since Windows 8 supports Powershell 5.0 and there's no point in holding to users who are running < Win8 os.

**Comment by Jaykul** [comment]
You should just do PowerShell 5 +

Given:
* Posh-Git is a **developer tool**, 
* PowerShell 5.1 is usable on Windows 7

Who on earth do you think is going to be affected if you choose to support only PowerShell 5+?

**Comment by dahlbyk** [comment]
Let's go with 5+… if that gets more people to upgrade, great.

posh-git 0.x is stable for those who can't.
