### ISSUE TITLE
Installation directions not so good

### ISSUE THREAD

**Issue by pbrianmackey** [dahlbyk/posh-git#440]
I'm not a fan of the recently updated installation directions.  It used to be that the first suggestion worked and was super easy.  Now I have to rely on a bunch of 3rd party tools and the first thing I tried doesn't even work after the painful process.  My suggestion is to re-add the old directions:

`(new-object Net.WebClient).DownloadString("http://psget.net/GetPsGet.ps1") | iex
install-module posh-git`

I keep a copy of this in my notes for new installs because the current readme is such a pita.

**Comment by rkeithhill** [comment]
The PowerShell community is making the switch off of the PSGet tool to the Microsoft supported PowerShellGet/PSGallery tools.  PSGet was great to have before having an official solution but it is getting a bit stale now.  The last update was ~5 months ago and that was someone removing their module from the PSGet directory.

So which version of PowerShell are you on?

**Comment by pbrianmackey** [comment]
I tried PowerShellGet.  I am on PS 5.1.14393.576.  I don't remember the specific error as my last try was in Oct. 2016.  This came up again because a co-worker of mine was unable to install posh-git.  I also recommended it to several other co-workers and none of them were able to install.  I had to copy that download string from my original post to each of their machines.

I haven't tried Chocolatey.  I've had good success with this tool on other products.

**Comment by rkeithhill** [comment]
Weird.  PowerShellGet should be the easiest of all options simply run a single command and yeah, you may be prompted to "trust" the PowerShell gallery but that's about it.  On occasion I see folks that don't have the NuGet package provider installed for some reason and there are instructions on how to boostrap those installs.  And the other case I see is $env:PSModulePath gets messed up so that after you Install-Module on posh-git the `Import-Module posh-git` command fails because it can't find the module in the standard ($env:PSModulePath) locations.
