### ISSUE TITLE
Request that the posh-git module install to $Env:ProgramFiles\WindowsPowerShell\Modules

### ISSUE THREAD

**Issue by David-Noble-at-work** [dahlbyk/posh-git#483]
I realize that customers might take this directory off the PSModulePath, but $Env:ProgramFiles\WindowsPowerShell\Modules is a better location than $Env:\tools in my opinion. It is a standard location for modules developed by the PowerShell community and is on the PSModulePath by default.

**Comment by rkeithhill** [comment]
If you use the `Install-Module` command in PowerShell v5 (or higher) it will install into the location you desire. Note, you have to be running as admin in order to have Install-Module install into that location.

From the issue, I take it you're using Chocolatey.  Over time we'd like to get more folks using the "native" PowerShell module management system (PowerShellGet).

**Comment by dahlbyk** [comment]
Please see https://github.com/dahlbyk/posh-git/issues/473#issuecomment-305372909.

(Closing as duplicate.)
