### ISSUE TITLE
Get-SshAgent return always 0

### ISSUE THREAD

**Issue by nlhommet** [dahlbyk/posh-git#575]
### System Details

- posh-git version/path:  `0.7.3` /  `C:\Program Files\WindowsPowerShell\Modules\posh-git`
- PowerShell version: `5.1.17134 revision 48`
- Git version: `version 2.17.0.windows.1`
- Operating system name and version: windows 10, version 1803

### Issue Description

Since last update of windows (1803), `Start-SshAgent` seems not working.

My profile.ps1
```
Import-Module "posh-git"
Start-SshAgent -Quiet
$ChocolateyProfile = "$env:ChocolateyInstall\helpers\chocolateyProfile.psm1"
if (Test-Path($ChocolateyProfile)) {
  Import-Module "$ChocolateyProfile"
}

Import-Module "Oh-My-Posh"
```

`Get-SshAgent` return always 0 and Git keeps prompting me for password.

**Comment by rkeithhill** [comment]
From PowerShell, what path does this command return `Get-Command ssh-agent.exe`?

**Comment by nlhommet** [comment]
```
CommandType     Name                                               Version    Source
-----------     ----                                               -------    ------
Application     ssh-agent.exe                                      7.6.0.0    C:\WINDOWS\System32\OpenSSH\ssh-agent.exe
````

**Comment by dahlbyk** [comment]
What happens if you run `ssh-agent` without the posh-git `Start-SshAgent`? The wrapper is really old, meant for the msys agent that ships with Git, not newer OpenSSH.

**Comment by nlhommet** [comment]
When I run `ssh-agent` nothing appear.
`Get-Service -Name 'ssh-agent'` return 
```
Status   Name               DisplayName
------   ----               -----------
Running  ssh-agent          OpenSSH Authentication Agent
```

**Comment by dahlbyk** [comment]
That seems promising. The other thing `Start-SshAgent` does is `ssh-add`, which should add private key identities from `~/.ssh/`.

**Comment by nlhommet** [comment]
`ssh-add -L` return my private key `ssh-rsa AAAAB...G1Q== ~/.ssh/id_rsa`

**Comment by dahlbyk** [comment]
But Git is still prompting you for your password?

I honestly have no idea if Git and Win32-OpenSSH are expected to play nicely together, or how to fix. I'll drop a note over in [Git for Windows Gitter](https://gitter.im/git-for-windows/git) to see if someone can help.

**Comment by nlhommet** [comment]
When I launch my powershell session, powershell prompts me my password for my private key.
```
Windows PowerShell
Copyright (C) Microsoft Corporation. Tous droits réservés.

Enter passphrase for ~/.ssh/id_rsa:
Identity added: ~/.ssh/id_rsa (~/.ssh/id_rsa)
Le chargement des profils personnels et système a duré 90504 ms.
 ⚡ > ~ >
```

**Comment by nlhommet** [comment]
Tx! it's working

**Comment by dahlbyk** [comment]
It sounds like `Start-SshAgent` should check if [`$sshAgent`](https://github.com/dahlbyk/posh-git/blob/3c18106f4054181911f44747d0470882e04d375a/src/SshUtils.ps1#L124-L137) path includes `OpenSSH`. If it does:

1. Confirm the service is running; if it's not, should we start it?
   * What if the service isn't registered?
2. Check if `GIT_SSH` aligns with OpenSSH usage; if it doesn't, warn with instructions.

**Comment by rkeithhill** [comment]
> It sounds like Start-SshAgent should check if $sshAgent path includes OpenSSH

Using Path might be a bit brittle since folks can grab the OpenSSH-portable package from [here](https://github.com/PowerShell/openssh-portable/releases) and install into a path of their choosing.  We could check this way - 
```posh
Get-Command ssh.exe | % FileVersionInfo | ? ProductVersion -match OpenSSH
```
Yup, we can only start the service if it has been registered.  If they installed the ZIP from the GH repo, the ssh-agent service won't be registered unless they've run the install-sshd.ps1 script.  That said, if they run the following command once from an Admin console, they'll never have to worry about starting ssh-agent again:
```posh
Get-Service ssh-agent | Set-Service -StartupType Automatic -PassThru | Start-Service
```
I suppose we could provide a warning if we detect that the `ssh.exe` in the path is the OpenSSH version and the user doesn't have `GIT_SSH` env var set appropriately.  We would probably want a way to allow folks to disable the warning (another import arg?).  

BTW it isn't a single env var.  At my company we use Git with both TFS 2015 and Bitbucket.  In order to get the cipher suite to work for both, I use this env var:
```
GIT_SSH_COMMAND = "C:\Program Files\OpenSSH\ssh.exe" -c aes128-cbc
```
And the quotes around the path are needed even if there are no spaces in that path.

**Comment by Halofreak1990** [comment]
Just stumbled upon this as I was looking for a solution to this very problem. After adding the GIT_SSH environment variable and rebooting, I am now only asked for the password once for each new PowerShell window, and not every time.

**Comment by rkeithhill** [comment]
If you have done the following:

1. Started the OpenSSH ssh-agent service (from C:\windows\system32\openssh)
2. Set up the ssh-agent service to start "Automatically"
3. Configured GIT_SSH to point to the OpenSSH ssh.exe e.g. `GIT_SSH = C:\WINDOWS\System32\OpenSSH\ssh.exe`
4. **And** used `ssh-add <private-key-file-path>` e.g. `ssh-add ~\.ssh\id_rsa` to add your private key file

You should never be asked for your passphrase.  In practice, I have found that I am sometimes asked for a passphrase after a Windows 10 insider build update.  That is always because the ssh-agent service isn't running.  As soon as I start it, I'm no longer asked for a passphrase.

**Comment by stereokai** [comment]
@rkeithhill Thank you! Lifesaver!

**Comment by dscho** [comment]
> `GIT_SSH = C:\WINDOWS\System32\OpenSSH\ssh.exe`

If, for some reason, you need to use a 32-bit `git.exe`, please use `GIT_SSH = C:\WINDOWS\SysNative\OpenSSH\ssh.exe` instead.

**Comment by AnthonyMastrean** [comment]
@rkeithhill I tried following your advice in https://github.com/dahlbyk/posh-git/issues/575#issuecomment-391386119 and ran into a hang, as described in https://github.com/PowerShell/Win32-OpenSSH/issues/1377... I'm not sure if I'm following up in the right place and thought you might have a more expert opinion 🙏

**Comment by yihuajack** [comment]
It probably because there was a bug in posh-git version 0.7.3 (also in 0.7.3.1). In Get-SshAgent function in GitUtils.ps1, the command `$sshAgentProcess = Get-Process | Where-Object { ($_.Id -eq $agentPid) -and ($_.Name -eq 'ssh-agent') }` would never correctly work because `$agentPid = $Env:SSH_AGENT_PID` is always different from the PID of the Windows process `ssh-agent.exe`. Besides, `return 0` was wrongly placed at the outer block. Therefore, `Get-SshAgent` would always return 0. Another consequence was that the function `Stop-SshAgent` was also invalid for the same reason. For the command `$proc = Get-Process -Id $agentPid -ErrorAction SilentlyContinue`, `Get-Process` could not get the actual process ID and `$proc` was always equal to 0 so that `Stop-Process` would never be executed (and it was not stopping the actual PID).
