### ISSUE TITLE
1.0 beta prompt incorrect with conemu

### ISSUE THREAD

**Issue by spooky** [dahlbyk/posh-git#592]
Because of the ssh-agent/windows update problems, I've updated to 1.0.0 beta posh-git but that seems to break the prompt integration with conemu (technically, cmder version 1.3.6 which uses conemu 180528).

The git part is placed at the end (after lambda sign in the second line) instead of after the direcotry in the first line (as it was with 0.7.3)

**Comment by dahlbyk** [comment]
Interesting, I wouldn't expect the console host to have any impact, assuming it's correctly handling ANSI control sequences. Can you share a screenshot, or text that demonstrates what's happening? Are you customizing `$GitPromptSettings` at all?

**Comment by dahlbyk** [comment]
Or are you using oh-my-posh?

**Comment by spooky** [comment]
using just posh-git, no customizations on the $GitPromptSettings. I should be able to share a screenshot around monday.

**Comment by rkeithhill** [comment]
Can you post the output you get from running `$PoshGitLastPrompt`?

**Comment by dahlbyk** [comment]
Does `$GitPromptSettings.AnsiConsole` return `false`? Try setting `$GitPromptSettings.AnsiConsole = $true`.

**Comment by dahlbyk** [comment]
FYI, we do check a ConEmu-specific environment variable for determining ANSI support: https://github.com/dahlbyk/posh-git/blob/dcb96a4dfce1c0f4fc1af1670e50b03f9bc1b080/src/PoshGitTypes.ps1

**Comment by CollinChaffin** [comment]
I have to disagree.  This broke how many of us in the community use it in conjunction with conemu because you completely destroyed backward compatibility from .73 to v1.0.  Anything we had in our profiles and prompts broke, and as a DEV myself for the life of me, I'm still trying to figure out why you went in that direction.

For instance, in .73 there was an actual example including various functions (like setting console titlebar for git etc.).  In version 1.0, however, you've now removed the example.ps1 for the profile and literally more than QUADRUPLED your lines of code to over 174 lines of code+text for a function named "Add-PoshGitToProfile" that literally does exactly what this SINGLE LINE of code does, no more - no less:

````
if ((Test-Path -LiteralPath $profilePath) -and ((Get-AuthenticodeSignature $profilePath).SignerCertificate) -and (!((@(Get-Content $profilePath -ErrorAction SilentlyContinue) -match 'posh-git').Count -gt 0))) { Add-Content -LiteralPath $profilePath -Value "`nImport-Module '$modulePath'" -Encoding UTF8}
````
It seems the profile addition functions/example in v1 now boils down (and is very limited to) "add import-module to your profile"...which also could have at that point probably even been left out of the code and mentioned in the readme. :)

So my question is, are we really saying in today's age of PoSH that the future direction of v1.0 can't at least continue to provide the handful of really useful services that were present in v7.3 and prior?  And if not, can I ask why and what the show-stopping hurdles are, so perhaps we can contribute solutions to help?

**Comment by rkeithhill** [comment]
> I have to disagree. 

What exactly in this issue are you disagreeing with?  Also, Add-PoshGitToProfile was added in v0.7x, not v1.

> can't at least continue to provide the handful of really useful services that were present in v7.3 and prior?

Which services (commands) are you referring to?  We've mostly added functionality in v1:
```

CommandType     Name                                               Version    Source
-----------     ----                                               -------    ------
Function        Add-PoshGitToProfile                               1.0.0.0    posh-git
Function        Expand-GitCommand                                  1.0.0.0    posh-git
Function        Format-GitBranchName                               1.0.0.0    posh-git
Function        Get-GitBranchStatusColor                           1.0.0.0    posh-git
Function        Get-GitDirectory                                   1.0.0.0    posh-git
Function        Get-GitStatus                                      1.0.0.0    posh-git
Function        Get-PromptConnectionInfo                           1.0.0.0    posh-git
Function        Get-PromptPath                                     1.0.0.0    posh-git
Function        prompt                                             1.0.0.0    posh-git
Function        TabExpansion                                       1.0.0.0    posh-git
Function        tgit                                               1.0.0.0    posh-git
Function        Update-AllBranches                                 1.0.0.0    posh-git
Function        Write-GitBranchName                                1.0.0.0    posh-git
Function        Write-GitBranchStatus                              1.0.0.0    posh-git
Function        Write-GitIndexStatus                               1.0.0.0    posh-git
Function        Write-GitStashCount                                1.0.0.0    posh-git
Function        Write-GitStatus                                    1.0.0.0    posh-git
Function        Write-GitWorkingDirStatus                          1.0.0.0    posh-git
Function        Write-GitWorkingDirStatusSummary                   1.0.0.0    posh-git
Function        Write-Prompt                                       1.0.0.0    posh-git
Function        Write-VcsStatus                                    1.0.0.0    posh-git
```
The big exception is the removal of the ssh functionality to the new `posh-sshell` module.

**Comment by CollinChaffin** [comment]
Well, if I do nothing else but upgrade from .73 to v1 like the OP above, and from the old profile example had this in my profile after of course a simple load of the module:
````
$Global:GitPromptSettings.EnableWindowTitle = "posh~git ~ <$SessionTitleName>"

....DO SOME OTHER LOADING.....

Start-SshAgent -Quiet
````
I am greeted with (mind you this is simply the removal of that method being populated by default and nothing to do with conemu) when the ONLY thing I changed was having ONLY 0.7.3 installed/loading on first screenshot, and simply upgraded it to either published 1.0.0.beta2, or even unzipped current Sept 15th build as screenshot #2 here:

Version 0.7.3:
![output1](https://user-images.githubusercontent.com/9301483/45861440-1dc0f700-bd32-11e8-983b-28d605ef30c3.gif)

Version 1.0.0.beta2 (either PSGallery or Github 9/15/2018)
![output2](https://user-images.githubusercontent.com/9301483/45861446-29142280-bd32-11e8-9aee-e7592cbd0788.gif)

As you can see, the screen turns red with this dumbed-down profile with any/all the SSHd commands prior to v1 no longer functioning at all, but things like the EnableWindowTitle not being properly initialized any longer and throwing errors.  With the exception of this specific test vm not having the ssh-agent in place (easily fixed) 0.7.3 is totally free of any big ugly red terminating errors.

I can also demonstrate loading the default Posh console without any profile at all, loading only psreadline v2 and posh-git beta v1.0, and issuing the same commands as in this screenshot and still receiving the same glaring terminating errors so it is easily reproducible and not in the way I am calling it which was originally straight out of the provided example profile info.  And since these errors are present when run in a straight Posh console without conemu even in the picture, so the conemu issue are simply snowballing from here.

Again, my point was not to upset you I was just trying to approach it logically that if you can afford to write and add almost 200 lines of text that is not "reusable" in any way and is hard-coded for a single purpose of adding a single hard-coded line of text (import-module posh-git) into the users' profile, then with that throughput it might not be unrealistic to think we could maybe find some ways to guard against breaking the users' of this module's profiles a little bit better and address these reproducible issues that tend to be a real PITA when they pop up after a simple "update-module". :)

**Comment by rkeithhill** [comment]
> my point was not to upset you

No worries and I'm not upset at all.  Was just trying to figure out what you disagreed with.  :-)

We plan to keep v0.7x around for a while so you don't have to upgrade to v1.  Typically the nature of a major version change is indicative of one or more breaking changes.  In order to do the following, it was necessary to make some breaking changes:

* Support Windows 10 new ANSI seq in the update console host.  This allows you to use 24 bit colors in your prompt.
* Support PowerShell Core on all the platforms it supports.
* Separate out the SSH functionality into its own module because the two sets of code are largely orthogonal.  
* Reorganize the GitPromptSettings to be more object-oriented and display color choices better and make it easier to customize the prompt without having to write your own custom prompt.

To fix your above errors - if you do not want to stick with v0.7x - install `posh-sshell`.  That will provide you with the `Start-SshAgent` command.  As for the EnableWindowTitle command, that changes to:
```
$GitPromptSettings.WindowTitle = "posh~git ~ <$SessionTitleName>"
```
Perhaps we should have a v0.7x to v1 migration guide?

**Comment by rkeithhill** [comment]
The problem with adding the SSH commands is that when the user does install `posh-sshell` there will be conflicting commands.  The one PowerShell picks will be based on import order.  And when the user installs `posh-sshell` they'll have to use `-AllowClobber`.  

Perhaps a better way to approach this is to use the `CommandNotFoundAction` e.g.:

![image](https://user-images.githubusercontent.com/5177512/46261755-550f7080-c4b5-11e8-87aa-b233cff1382f.png)

The above is just a proof of concept.  We'd have to add all the ssh commands to the list and also check to see if there's an existing CNFA handler and if so, then invoke it - returning whatever it returns.

**Comment by dahlbyk** [comment]
CNFA could work, though it's weird that it's not built to be composable.

Could the shims check if posh-sshell is installed and pass-thru? Could we avoid exporting the shims if we detect it's installed?

**Comment by rkeithhill** [comment]
Passthrus still incur the issues of duplicate commands i.e. import order and requires `-AllowClobber`.  We can conditionally export the shims if posh-sshell is not installed.  

Overall I think the CNFA approach is better - certainly much simpler to implement.  The lack of composability is unfortunate but is no different than the TabExpansion function where we invoke the previous TabExpanion function (if there was one).

**Comment by JamesSkemp** [comment]
I'm running into a similar issue as @spooky was.

I was running Cmder on Windows 10, with PowerShell 6.0.1, posh-git 0.7.1.

Upgraded to PowerShell 6.1.0 and my prompt and output text ended up the same color. Upgraded to 0.7.3, noticed that posh-git 1.0.0 had PS Core support, so upgraded to 1.0.0 beta2.

![image](https://user-images.githubusercontent.com/904615/47105735-645b2180-d20a-11e8-8de0-24834c0e3f2e.png)

I think these were the last debug steps before this issue swung on a slight tangent. :)

**Comment by rkeithhill** [comment]
What does your prompt function look like?  Execute `get-command prompt | % definition` and list the output here, if you don't mind.

**Comment by JamesSkemp** [comment]
Sorry for the delay:

    $realLASTEXITCODE = $LASTEXITCODE
    $host.UI.RawUI.WindowTitle = Microsoft.PowerShell.Management\Split-Path $pwd.ProviderPath -Leaf
    PrePrompt | Microsoft.PowerShell.Utility\Write-Host -NoNewline
    CmderPrompt
    Microsoft.PowerShell.Utility\Write-Host "`nλ " -NoNewLine -ForegroundColor "DarkGray"
    PostPrompt | Microsoft.PowerShell.Utility\Write-Host -NoNewline
    $global:LASTEXITCODE = $realLASTEXITCODE
    return " "

**Comment by rkeithhill** [comment]
Hmm, that is not the default posh-git `prompt` function.  I'm guessing some other module is providing your prompt function.  It could be that it's hooking the `posh-git` prompt and then displaying it via the `PostPrompt` command invocation, which would explain why the posh-git status shows up after the Cmder prompt.  Do you get any source/module info if you execute: `get-command PostPrompt`?

**Comment by JamesSkemp** [comment]
| CommandType | Name | Version | Source |
| --- | --- | --- | --- |
| Function | PostPrompt | | |

I am using Cmder on top of ConEmu, but starting ConEmu directly results in the same behavior.

No changes to ConEmu/Cmder with the other changes I made.

**Comment by rkeithhill** [comment]
What are the contents of `PostPrompt` - run `Get-Command PostPrompt | % Definition`.

**Comment by JamesSkemp** [comment]
Hmm. It appears to be nothing?

**Comment by rkeithhill** [comment]
Thanks for checking.  I have found that the prompt function is supplied by Cmder:

https://github.com/cmderdev/cmder/blob/c5a6afbf5b0d15703da4ecef75d0e845c9c27707/vendor/profile.ps1#L104-L126

The posh-git status summary is displayed by the call to `checkGit()` which in turn calls the posh-git command `Write-VcsStatus`.  So one change in posh-git v1 is to support VT sequences for hosts that support it.  What this effectively means is that the `Write-VcsStatus` command will not use `Write-Host` to write the git status on a host that supports VT. In that case, it returns a string that contains the git status decorated with VT esc sequences to color various part of the status.  So `checkGit()` returns a string but that string isn't displayed until **after** the prompt function returns which is also after all the `Write-Host` calls.  

Try setting `$GitPromptSettings.AnsiConsole = $false` and see if that clears this up.  When this setting is `$false`, posh-git reverts back to using `Write-Host`.

**Comment by rkeithhill** [comment]
@dahlbyk If the above fix works, we could use the existence of `$env:CMDER_ROOT` to default AnsiConsole to $false.  See https://github.com/cmderdev/cmder/blob/master/vendor/profile.ps1#L26

**Comment by JamesSkemp** [comment]
Thanks for digging deep! That appears to semi-resolve the issue:

Now:
![image](https://user-images.githubusercontent.com/904615/47154740-bbafcf00-d2a8-11e8-94e1-c56af003d673.png)

Before I decided to update software that wasn't broken ;) :
![image](https://user-images.githubusercontent.com/904615/47155139-c1f27b00-d2a9-11e8-9ab4-356a8473bb52.png)


Only differences are the presence of the `PS` (which may be a PS 6.1.x thing - I'm going to spend some time looking into it) and that it's per-session/reverts back to true (which I'm assuming is to be expected / it's checked and set on every startup).

Your suggestions sound good to me; please let me know how/if I can assist in anyway!

**Comment by rkeithhill** [comment]
Thanks.  We're getting closer.  That `PS >` usually happens when the prompt function returns no string e.g.:
```
function prompt { Write-Host "$pwd> " -NoNewline }
```
or there is an error generated in the prompt:
```
function prompt { Write-Host "$pwd> " -NoNewline; throw "oops"; return " " }
```
I suspect it is the latter.  Could you open up a fresh cmder console and after you get your first prompt, execute: `$error`.

**Comment by JamesSkemp** [comment]
Cmder error. :)

> Get-command : The term 'vim' is not recognized as the name of a cmdlet, function, script file, or operable program.
> Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
> At D:\Downloads\cmder\vendor\profile.ps1:44 char:5
> +     Get-command -Name "vim" -ErrorAction Stop >$null
> +     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> + CategoryInfo          : ObjectNotFound: (vim:String) [Get-Command], CommandNotFoundException
> + FullyQualifiedErrorId : CommandNotFoundException,Microsoft.PowerShell.Commands.GetCommandCommand

Unless you see something, I'll raise it as an error with them? https://github.com/cmderdev/cmder/blob/master/vendor/profile.ps1#L44

(I did upgrade Cmder to the current version from what I was at to see if that would resolve it; it did not.)

**Comment by rkeithhill** [comment]
Hmm, but looking at that code, they catch the error and that code isn't executed within the prompt so that shouldn't be the cause of this problem.  Keep in mind that the `$error` collection records **all** errors whether or not they were caught.  Was there only that one error?

**Comment by JamesSkemp** [comment]
Good to know.

It was the only error reported. Went into a git repo and ran a few other commands that might verify that:

![image](https://user-images.githubusercontent.com/904615/47168200-e9574100-d2c5-11e8-89c7-79a74f5d6e22.png)

**Comment by rkeithhill** [comment]
I think this is something we're doing in posh-git v1.  I can replicate it with the following prompt function in a regular PowerShell console:
```
function prompt { $GItPromptSettings.AnsiConsole = 0;  Write-VcsStatus; " " }
```
Now that I have a repro I should be able to figure out what is going on here.  Hopefully we will have a beta3 out in a few weeks with a fix for this.

**Comment by JamesSkemp** [comment]
Excellent. Thank you again for helping to troubleshoot this!

**Comment by rkeithhill** [comment]
And voila, I have figure it out.  When AnsiConsole is set to 0 (off), Write-VcsStatus is returning an empty string.  Returning an empty (or no) string from a prompt will result in PowerShell displaying `PS>` because it thinks that prompt function failed and the user should be given some default prompt.  But when you return a collection of strings - the empty string returned by Write-VcsStatus and the `" "`, PowerShell gets confused and displays the default prompt e.g.:
```
function prompt { Write-Host "$pwd> " -NoNewline; ''; ' ' }
```
Results in this prompt `C:\Users\hillr\Git\KLM> PS>`.  The good news is that I've already queued up a PR to fix this (PR #617).  So I think the only additional thing we need to add is a check for `$env:CMDER_ROOT` that disables the AnsiConsole setting by default.

**Comment by rkeithhill** [comment]
This should be fixed by #617 which should be available in 1.0.0-beta3.

**Comment by dothar** [comment]
Hi, Im still having this issue:
![image](https://user-images.githubusercontent.com/55310024/118019133-04c84280-b32f-11eb-961b-2d14c90886fa.png)

I tried to set this the cmder/config/user_profile.ps1 file but it works only before the second prompt input

```
[ScriptBlock]$PostPrompt = {
    $GitPromptSettings.AnsiConsole = false;
}
```

Also it displays the "PS>" when Im not in a git repository
![image](https://user-images.githubusercontent.com/55310024/118019527-77d1b900-b32f-11eb-9f0e-a422f8eb0d97.png)

**Comment by Lsdenis** [comment]
Hey, everyone!
Same problem here:
![image](https://user-images.githubusercontent.com/5397940/119845613-19513100-bf12-11eb-940a-d7cba9e4c079.png)

$GitPromptSettings.AnsiConsole = $false fixes the problem, but only in current session.
$error returns same error as @JamesSkemp attached years ago.

**Comment by rkeithhill** [comment]
@dothar @Lsdenis  You need to put that line in your profile script. From PowerShell, execute `notepad $PROFILE.CurrentUserAllHosts` if you see a line in that file like `Import-Module posh-git` put the line `$GitPromptSettings.AnsiConsole = $false` after it.  If you don't see the import-module line in this file OR the file does not exist, then try `notepad $PROFILE.CurrentUserCurrentHost`.

Essentially you are looking for the `Import-Module posh-git` command in one of your profile scripts and you're going to add the line `$GitPromptSettings.AnsiConsole = $false` after the module is imported.  Also note that you are setting that value to `$false` and NOT `false`.

**Comment by Lsdenis** [comment]
hey @rkeithhill!
thanks for the info, however it doesn't work for me :(

tried both `CurrentUserAllHosts` and `CurrentUserCurrentHost`.
Made some small investigations:
* if you make changes here:
![image](https://user-images.githubusercontent.com/5397940/120500627-ac361380-c3c9-11eb-8c6c-0c426ad2d7ff.png)
it doesn't help, with or without > $null, was lazy to google syntax :)
* if you make changes like this: 
![image](https://user-images.githubusercontent.com/5397940/120500883-d7206780-c3c9-11eb-9b17-c090d2849aeb.png)
works fine except first line :)

Hope that helps.

Got some errors during investigations, all of them were about 'AnsiConsole doesn't exists' :)
![image](https://user-images.githubusercontent.com/5397940/120501044-f6b79000-c3c9-11eb-9043-6b4e2877156d.png)

**Comment by rkeithhill** [comment]
Your `Import-Git()` function is only importing posh-git and executing your `$GitPromptSettings.AnsiConsole = false` **IF** you have a version of posh-git less than or equal to `0.6.1.20160330`.  That script will not execute for posh-git `1.0.0`. 

That is not a posh-git installed function.  I have no idea what is up with that version check.  Anyway, change that function to:

```powershell
function Import-Git() {
    Import-Module posh-git > $null
    $GitPromptSettings.AnsiConsole = false
    $true
}
```

And see how it behaves.

**Comment by Lsdenis** [comment]
Thanks, @rkeithhill, works just as needed!

For anyone else who's using that snipper replace `false` with `$false` :)

**Comment by rkeithhill** [comment]
Thanks for catching that (copy/paste error). I updated the snippet above.
