### ISSUE TITLE
Gray and DarkGray are swapped

### ISSUE THREAD

**Issue by ExE-Boss** [dahlbyk/posh-git#672]
### System Details

- posh-git version/path: 1.0.0 beta3 C:\Program Files\PowerShell\Modules\posh-git\1.0.0
- PowerShell version: 6.1.3
- Git version: 2.21.0.windows.1
- OS: Microsoft Windows NT 10.0.17763.0

### Issue Description

[`Get-VirtualTerminalSequence`](https://github.com/dahlbyk/posh-git/blob/master/src/AnsiUtils.ps1#L49) returns the following for:
```
Gray:     [38;2;128;128;128m
DarkGray: [38;2;169;169;169m
```

### Expected output:
```
Gray:     [38;2;169;169;169m
DarkGray: [38;2;128;128;128m
```

---

Preferably, `ConsoleColor` would be checked before `HTMLColor`.

**Comment by rkeithhill** [comment]
We went back and forth on which to support first. We decided to support HtmlColor names first because supplying a ConsoleColor is easy - just set the color to `([ConsoleColor]::Gray)`.  Also, when you use a ConsoleColor you're going to get the color as defined by the index of your console host color tab:
```
PS> &(gmo posh-git) { EscapeAnsiString (Get-VirtualTerminalSequence ([ConsoleColor]::Gray)) }
`e[37m

PS> &(gmo posh-git) { EscapeAnsiString (Get-VirtualTerminalSequence ([ConsoleColor]::DarkGray)) }
`e[90m
```
Regarding the HtmlColor definitions of `Gray` and `DarkGray`, we  are just using what the System.Drawing.ColorTranslator.FromHtml() method is returning. If you think those values are wrong, you should submit an issue to the CoreFx repo.

**Comment by dahlbyk** [comment]
It never occurred to me that HTML/CSS/SVG `Gray` would be darker than `DarkGray`, but here we are:

![image](https://user-images.githubusercontent.com/133987/55565237-17d3a780-56bf-11e9-8919-09198432b25f.png)

https://en.wikipedia.org/wiki/Web_colors
