### ISSUE TITLE
Get merge/conflict status

### ISSUE THREAD

**Issue by brandonmcclure** [dahlbyk/posh-git#686]
### System Details

- posh-git version/path:
- PowerShell version: 1.0.0 beta2 C:\Program Files\WindowsPowerShell\Modules\Posh-Git
- Git version: git version 2.20.1.vfs.1.1.104.g2ab7360
- Operating system name and version: 
Platform ServicePack Version      VersionString
-------- ----------- -------      -------------
 Win32NT             10.0.17134.0 Microsoft Windows NT 10.0.17134.0

### Issue Description

This is a feature request. I am automating an integration process that is triggered via a pull request. The process will merge the developer's feature branch with an integration branch, and then our CI system will build/deploy that integration branch. 

I want to be able to comment on the PR if the merge failed/has conflicts, and would like to be able to explain which lines are conflicting (and who the commiter is so that the 2 developers can collaborate on resolving the conflict(s) 

I would love if Posh-Git could give me information such as is a merge in progress, how many conflicts there are (and whom is to blame). I think the way I would like it to work is to include that information inside of `Get-GitStatus`, then my automation script becomes Check `Get-GitStatus` and if there is a conflict report to the CI system with the information surfaced.

**Comment by brandonmcclure** [comment]
I would be interested in writing some code for this feature if someone can provide some guidance on how they want this feature to work/be designed so that I can ensure I am starting off on the right path.

**Comment by dahlbyk** [comment]
Sorry for the delayed response, @brandonmcclure.

posh-git already includes conflicted files in the `Get-GitStatus` response as `$GitStatus.Index.Unmerged` and `$GitStatus.Working.Unmerged` (they should match). They drive the prompt's `!` status/counts:

```text
[conflict-test +0 ~0 -0 !1 | +0 ~0 -0 !1 !]
```

That said, I don't think we'll want to teach posh-git how to get the more detailed information you seek, since we can `Get-GitStatus` for every prompt. You'll get better performance from more specific git functions, e.g. combine [`git ls-files --unmerged`](https://stackoverflow.com/a/11014518/54249) and [`git blame -L '/^<<<</,/^>>>>/' -- <file>`](https://stackoverflow.com/a/41320247/54249).

Glad to help you polish such a script (or post a question to Stack Overflow if you get stuck), but I'm going to close this as a posh-git issue.
