### ISSUE TITLE
Put current directory and Git status in ConEmu status bar

### ISSUE THREAD

**Issue by ctwise** [dahlbyk/posh-git#732]
### System Details

- posh-git version/path: 0.7.3  C:\Program Files\WindowsPowerShell\Modules\posh-git\0.7.3
- PowerShell version: 5.1.17763.771
- git version 2.25.0.windows.1
- OS: Microsoft Windows NT 10.0.17763.0

### Issue Description

ConEmu supports setting the status bar text. It would be extremely nice if we could output the path and the Git status to the ConEmu status bar _instead_ of to the prompt.

You can use raw escape codes or the command-line utility, e.g.,:

ConEmuC -GuiMacro Status 1 "My path and my git status"

You can see the documentation for this ConEmu GuiMacro here:

https://conemu.github.io/en/GuiMacro.html#Status

And the escape codes behind it are here:

https://conemu.github.io/en/AnsiEscapeCodes.html

Thanks!

**Comment by dahlbyk** [comment]
We've collected a handful of hacks to make posh-git work well with various hosts, but I don't think I'd want to maintain code specific to ConEmu.

That being said, we should export everything you'd need to define your own `prompt` that will block ours, e.g.

```pwsh
Copy-Item function:\prompt function:\global:OrigPrompt
function prompt {
  $s = "$(Write-Prompt $GitPromptSettings.DefaultPromptPath.Expand()) $(Write-VcsStatus)"
  ConEmuC -GuiMacro Status 1 $s
  OrigPrompt
}
```

Put this before you posh-git and you should be close. Or write whatever you want for a prompt, instead of using the built-in one.
