### ISSUE TITLE
Tab auto-complete regression

### ISSUE THREAD

**Issue by ExE-Boss** [dahlbyk/posh-git#733]
## System Details

- posh-git version: <https://github.com/dahlbyk/posh-git/commit/efed853aa5c5ab235ded5c1a191fac189470eb28>
- PowerShell version: v6.2.3

## Issue Description

[**PR&nbsp;#711**](https://github.com/dahlbyk/posh-git/pull/711) caused&nbsp;a&nbsp;regression that&nbsp;broke tab&nbsp;completion on&nbsp;**PowerShell&nbsp;>=&nbsp;6**,&nbsp;causing:
```
git <command> \t
```

To&nbsp;incorrectly expand&nbsp;to:
```
git <command> <command>
```

Instead&nbsp;of&nbsp;what it&nbsp;expanded&nbsp;to in&nbsp;commit&nbsp;<https://github.com/dahlbyk/posh-git/commit/89dafc1f37d9a44917d5ce6a84e889e54c6f98b9>, which&nbsp;is&nbsp;what I&nbsp;was&nbsp;forced to&nbsp;roll&nbsp;back&nbsp;to.

**Comment by rkeithhill** [comment]
What do you get from the built-in argument completion for `cd ~; gci \w`?

**Comment by rkeithhill** [comment]
Also, do you have a specific repro because I haven't been able to repro what you are seeing?

**Comment by eXpl0it3r** [comment]
Not sure if it's actually an regression, currently the new git command `git switch <branch>` doesn't work with tab-completion though.

**Comment by rkeithhill** [comment]
If you git clone the repo, it has support for git switch.  Has had it for a few months now.  But we haven't published a new beta in almost a year and I'm not sure when the next beta will be published.  I recommend that you git clone this repo and import the module by path.

**Comment by theaquamarine** [comment]
Would you be open to an update to 0.x that adds support for switch and restore?

**Comment by rkeithhill** [comment]
Yes and no.  Obviously adding features to 0.x would help folks but I'd really like to "nudge" folks to 1.0.  That said, 1.0 is still beta so that's hard to do until we release a stable version of v1.  Supporting multiple versions is not ideal when we have such a small set of folks trying to maintain this module.  Whining aside ;-), I would accept a PR to add that functionality to 0.x but who knows when a new version of 0.x would be published.

**Comment by cdonnellytx** [comment]
I dug into this a bit... the main issue is that the handler for `Register-ArgumentCompleter` returns the "Text" for an autocomplete as `git <command>` with no trailing space, instead of the expected `git <command> ` with at least one trailing space.    The regexes in `GitTabExpansionInternal` expect at least one space after the command.  

An annoying side-effect of this is that  `Register-ArgumentCompleter`  completions aren't unregistered if you unload the module, meaning debugging involves having to open a new PowerShell process for each attempt at debugging.

**Comment by rkeithhill** [comment]
@cdonnellytx Thanks for taking the time to debug this.  If `Register-ArgumentCompleter` is removing the space between the command and the tab, then there's a challenge - how do we distinguish `git checkout \t` from `git che\t`?  Perhaps the space still exists in one of arg completer params?
