### ISSUE TITLE
Wrong Windows 10 user path is being used by posh-git - Powershell Core 6.2.7 & Windows Terminal

### ISSUE THREAD

**Issue by Melander** [dahlbyk/posh-git#793]
**Versions**
**OS**: Windows 10 Enterprise (1909)
**posh-git**: ~\Documents\PowerShell\Modules\posh-git\0.7.3
**Git**: 2.28.0.windows.1 (64-bit)
**PowerShell**: 6.2.7/7.0.3
**$Home**: C:\Users\<Username>

**Expected result**
Git clone should work.

```console
PowerShell 6.2.7
Copyright (c) Microsoft Corporation. All rights reserved.

https://aka.ms/pscore6-docs
Type 'help' to get help.

PS C:\git> git clone git@<giturl>:<repo>gitrepo.git
Cloning into '<gitrepo>'...
remote: Enumerating objects: 62, done.
remote: Counting objects: 100% (62/62), done.
remote: Compressing objects: 100% (35/35), done.
remote: Total 126 (delta 24), reused 58 (delta 20), pack-reused 64
Receiving objects: 100% (126/126), 23.21 KiB | 609.00 KiB/s, done.
Resolving deltas: 100% (49/49), done.
PS C:\git>
C:\git> $Home
C:\Users\<Username>
C:\git>
```

**Actual result**
Installed posh-git using the following command:

```console
Install-Module -Name 'posh-git'
```

Posh-git enabled in Microsoft.PowerShell_profile.ps1, also the only line inside the profile.
```
Import-Module -Name posh-git
```

```console
PowerShell 6.2.7
Copyright (c) Microsoft Corporation. All rights reserved.

https://aka.ms/pscore6-docs
Type 'help' to get help.

Loading personal and system profiles took 1122ms.
C:\git> git clone git@<giturl>:<repo>gitrepo.git
Cloning into 'gitrepo'...
Could not create directory '/h//.ssh'.
The authenticity of host '<gitaddress> (<git-ip>)' can't be established.
ECDSA key fingerprint is SHA256:<fingerprint>.
Are you sure you want to continue connecting (yes/no/[fingerprint])? yes
Failed to add the host to the list of known hosts (/h/.ssh/known_hosts).
git@<giturl>: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
C:\git>
C:\git> $Home
C:\Users\<Username>
C:\git>
```

By the looks of it posh-git is using the wrong user home path.

**Comment by rkeithhill** [comment]
Using posh-git via `git clone` is not the typical way we expect **users** to get posh-git.  Users should use `install-module posh-git` followed by `import-module posh-git`.  And to make posh-git load on PS startup, users should execute `Add-PoshGitToProfile` after importing posh-git.

Folks who contribute to posh-git, need to be able to run from a git clone dir.  After you `git clone` you need to import the module by path:
```
Import-Module C:\git\posh-git\src\posh-git.psd1
```

If your issue is that you can't successfully clone posh-git, you might want to file an issue with github.com.  I can tell you that this clone URL works fine for me:
```
git clone https://github.com/dahlbyk/posh-git.git
```

**Comment by Melander** [comment]
Hi @rkeithhill, thanks for a quick response.
I think you got me wrong, I installed posh-git via the command you wrote ```install-module posh-git```, not through git clone.

After I installed and enabled the posh-git module the "git clone" command does not work in Powershell Core 6.2.7 and gives me the error ```Could not create directory '/h//.ssh'.```.
Oh, I haven't actuallt thought about it until now, but and I'm using Powershell Core inside Windows Terminal, that might also have something to do with it, but regardless, when I disable the posh-git module the git clone command works again.

**Comment by rkeithhill** [comment]
I don't think this is an issue with PS Core / Windows Terminal because that is the configuration that I use.   Are you saying that any git clone using ssh won't work or just git cloning posh-git? 

Keep in mind that Git cloning via SSH on Windows takes a fair amount of set up or it won't work i.e. installing and configuring OpenSSH Server as well as the ssh-agent service and adding ssh keys and configuring Git to use ssh.

FWIW I use ssh cloning at work (Bitbucket servers) along with posh-git v1.0.0-beta4 and have never had an issue - well except for the occasional server glitch.

**Comment by Melander** [comment]
Any git clone I make in Poweshell Core with posh-git enabled fails with that error ```Could not create directory '/h//.ssh'```, if I do the same git clone in Powershell Core with posh-git disabled or in cmd it works as expected. 

I've just made a complete reinstall of my computer, and I'm a bit confused since the same Windows terminal/Powershell/posh-git setup worked on my previous Windows 10 installation where I actually had Powershell Core 7.0.3 installed. I tried with 7.0.3 on this computer first but with the same error, then I read that posh-git does not support 7.0.3 so I downgraded to Powershell 2.6.7, but sadly with no luck.

The big differences are that my computer is now connected to a domain and I use Windows 10 Enterprise instead of Pro.

**Comment by Melander** [comment]
I might have to try posh-git beta, hopefully that solves my issue since I really do like posh-git! 👍 👍

**Comment by rkeithhill** [comment]
>  I read that posh-git does not support 7.0.3
posh-git supports PS 5, 6 and 7.  

Try install v1 beta using `Install-Module posh-git -AllowPrerelease -Scope CurrentUser -Force`.  v1 has VT/ANSI sequence support so that works better with Windows Terminal.

**Comment by Melander** [comment]
@rkeithhill, I installed v1 beta and now git clone works without any errors! 👍 Thanks!
