### ISSUE TITLE
poshgit doesn't report change values when inside the .github directory

### ISSUE THREAD

**Issue by jethas-bennettjones** [dahlbyk/posh-git#873]
### System Details

- posh-git version/path: 1.0.0  ~\Documents\PowerShell\Modules\posh-git\1.0.0
- PowerShell version: 7.1.4
- git version 2.31.1.windows.1
- OS: Microsoft Windows NT 10.0.19043.0

### Issue Description

I am experiencing a problem with seeing the git status in the prompt when I am in the .github directory.

Here is what I see:
![image](https://user-images.githubusercontent.com/62298251/135617239-9ebc5c6c-ce19-4a9c-8ca9-980a306ed6cb.png)

**Comment by dahlbyk** [comment]
Good find! There are two places we try to detect if we're inside a `.git` folder, and it turns out `path/to/.github` starts with `path/to/.git`:
- https://github.com/dahlbyk/posh-git/blob/5a87e8a196d13395f978d774f80dedb40d43b85e/test/Shared.ps1#L93
- https://github.com/dahlbyk/posh-git/blob/b79c2dc39c9387847642bc3b38fa2186b29f6113/src/GitUtils.ps1#L440

Marking as Up-for-Grabs, if someone wants to take a crack at it.

**Comment by jethas-bennettjones** [comment]
@dahlbyk I took a stab at it. Please check out the PR.
