### ISSUE TITLE
Posh Git Module Gets Blocked by Windows Action Guard

### ISSUE THREAD

**Issue by oliverlabs** [dahlbyk/posh-git#939]
### System Details

- posh-git version/path:
- PowerShell version:
- Git version:
- Operating system name and version:

### Issue Description

I am experiencing a problem with... ConsoleMode.ps1 is being blocked by Windows Action Guard.

**Comment by oliverlabs** [comment]
<img width="815" alt="git-posh-screen" src="https://user-images.githubusercontent.com/70239916/212319451-51e117c4-d134-47f7-ba08-6bf29ea2cd72.png">

**Comment by rbuckton** [comment]
As a workaround you can add an exclusion in Windows Security for that specific file, though that does potentially weaken the security of your Windows device.

**Comment by patridge** [comment]
I was just able to fix this on my system. Defender completely deletes that ConsoleMode.ps1 file no matter where it is created, including during reinstall, which made things a challenge. Here are the steps I needed to get back to working again.

1. Add exclusion to parent folder to allow you to install the new ConsoleMode.ps1 in the future: `C:\Users\{username}\Documents\PowerShell\Modules\posh-git\1.1.0\`
1. Add exclusion to the entire Temp folder where the posh-git installer will create the same file when you try to reinstall: `C:\Users\{username}\AppData\Local\Temp\`.
1. Reinstall posh-git: `PowerShellGet\Install-Module posh-git -Scope CurrentUser -Force`
1. Remove exclusion for entire Temp folder, since that's probably a bit too expansive. (You need to keep the first exclusion in place until Defender stops trying to delete ConsoleMode.ps1 every time.)

**Comment by oliverlabs** [comment]
Thanks, Adam, @patridge. This worked for me. For those who don't know how to add an exclusion, use the following command: 

`Add-MpPreference -AttackSurfaceReductionOnlyExclusions "[PATH]"`

**Comment by patridge** [comment]
Ooh...I wonder if that would allow you to preemptively add non-existent files that you _plan_ to have exist soon. That would prevent needing to add exemptions that are more broad than strictly necessary.

Oddly, adding via that system doesn't appear to surface them in the Exclusions page of the Security section of the Windows Settings app. I wonder where those get stored.

**Comment by oliverlabs** [comment]
Yes, it would. You can add both files and folders to the exception.
