### ISSUE TITLE
Create core git commands as PowerShell cmdlets

### ISSUE THREAD

**Issue by powercode** [dahlbyk/posh-git#97]
Hi all,

I would like to see posh-git move into a more full fledged PowerShell citizen.
One of the hall marks of that would be cmdlets outputting objects for the core functionality.

My initial suggestions would be 
Get-GitLog
Get-GitStatus
and for bonus points, just to show the power of PowerShell,
Convert-GitBranch (for git filter-branch)

Convert-GitBranch -Branch master -Begin{
   $NameTable = @{}
   ... code to fill $NameTable
} -Process {
   param([Commit] $Commit)  
   $Commit.Author.Name = $NameTable[$Commit.Author.Name] 
}

I'd be glad to chip in on this on. I'm a git/github newbie, but experienced with PowerShell, both as a user/scripter and as a cmdlet developer.

Is libgit2sharp mature enough to be able to do this?

**Comment by NiloCK** [comment]
This is an old issue which I'm sure people still have interest in. I'm fairly new to both powershell and git so forgive me if I'm off base with this.

My own take on this issue is that it's more immediately useful, and perhaps a gentler starting point to get the ball rolling, to override the regular git commands such that they return sensible objects/collections for the pipe.

Eg: `git status | gm' currently reports that the passed object is a string, namely the output that's printed when the command is run, whereas ideally a collection of <a href="https://github.com/libgit2/libgit2sharp/blob/vNext/LibGit2Sharp/StatusEntry.cs">StatusEntry</a> objects would be coming across.

The benefit here is that it can be introduced piecewise with no usability hurdles on existing git / posh-git users, and little need for consensus building with respect to naming convention, coverage, etc.

**Comment by Jaykul** [comment]
Hey, if anyone is still paying attention here, a couple of us are playing around with trying to actually write this, and I'd like some feedback on a design question:
PoshCode/PSGit#10

**Comment by dahlbyk** [comment]
Closing in deference to PSGit
